// 자동 생성 (scripts/export-bg-materials.mjs) — 손으로 고치지 않는다.
// 새 터 꾸미기 소재: assets/background-materials-simple.png (2026-10-07 사용자 확정). 기본 길·지형 교체용이 아니라 유저가 놓는 꾸미기만.
export const BG_PALETTE: Record<string, string> = {
  "a": "#c9baa9",
  "b": "#85a978",
  "c": "#a1c08c",
  "d": "#eae4d7",
  "e": "#b4cc9a",
  "f": "#608563",
  "g": "#72976d",
  "h": "#8d6652",
  "i": "#a97d60",
  "j": "#94ac97",
  "k": "#f2d9b2",
  "l": "#a99a8c",
  "m": "#c3b4a4",
  "n": "#b4a697",
  "o": "#ceab89",
  "p": "#dfc09b"
}

export const BG_ART: Record<string, string[]> = {
  "treeBig": [
    ".......dbbbb......",
    "......ccccbbbc....",
    "....dceeeebbbb....",
    "...ceeeeeebbbb....",
    "..ceeeeeecbbbgfg..",
    "..ceeeeeebbbbffff.",
    ".ceeeeeebbbbbffff.",
    ".ceeecbbbbbbffffff",
    "bbcebbbbbbbbffffff",
    "bbbbbbbbbbbfffffff",
    "bbbbbbbbbgffffffff",
    "ebbbbbbbfffffffffb",
    ".cbbbfffhihfffffj.",
    "..gfffffiihfffff..",
    "...fffffiihffffj..",
    ".....fffiihff.....",
    "........iih.......",
    "........iih.......",
    "........iih.......",
    "........iih......."
  ],
  "treeTall": [
    "....cccc....",
    "...cceebb...",
    "..eeeeebbb..",
    "..ceeeebbbb.",
    ".beeeeebbbb.",
    ".ceeeebbbbb.",
    ".ceeeebbbbff",
    "cceeebbbbfff",
    "bbebbbbbbfff",
    "bbbbbbbbbfff",
    "bbbbbbbbffff",
    "bbbbbbbfffff",
    "bbbbbbffffff",
    ".bbbbffffff.",
    "..ffffffff..",
    "..ffffffff..",
    "...ffihff...",
    ".....ih.....",
    ".....ih.....",
    ".....ih.....",
    ".....ih....."
  ],
  "treeSmall": [
    "...ccc...",
    "..ceebb..",
    ".ceeebbb.",
    "ceeebbfff",
    "bbebbbfff",
    "bbbbbffff",
    ".bbfffff.",
    "..ffhff..",
    "...dh....",
    "...dh....",
    "...dh...."
  ],
  "bush": [
    ".....ccba...",
    "...cceebb...",
    "..ceeeebbb..",
    ".ceeeeebbff.",
    "cceeeebbbfff",
    "bbbebbbbffff",
    "bbbbbbbbffff",
    "cbbbbbbffffj",
    ".bbbbbffff.."
  ],
  "grassTuft": [
    "..eb..",
    "..bc..",
    "b.bj.b",
    "bfbbbg",
    ".bggf.",
    ".gfgf."
  ],
  "flower": [
    "..k..",
    "dkdkk",
    "kk.kk",
    "..l..",
    "..bcb",
    "b.bbg",
    "bgbf.",
    ".bf.."
  ],
  "rocks": [
    "..ama..",
    ".aaam..",
    "aaanma.",
    "maanaan",
    "....amn"
  ],
  "grass": [
    "cccccccccccccccc",
    "cccccccccccccccc",
    "cccccccccccccccc",
    "cccccccccccccccc",
    "cccccccccccccccc",
    "cccccccccccccccc",
    "cccccccccccccccc",
    "cccccccccccccccc",
    "cccccccccccccccc",
    "cccccccccccccccc",
    "cccccccccccccccc",
    "cccccccccccccccc",
    "cccccccccccccccc",
    "cccccccccccccccc",
    "cccccccccccccccc",
    "cccccccccccccccc"
  ],
  "sand": [
    "kkkkkkkkkkkkkkkk",
    "kkkkkkkkkkkkkkkk",
    "kkkkkkkkkkkkkkkk",
    "kkkkkkkkkkkkkkkk",
    "kkkkkkkkkkkkkkkk",
    "kkkkkkkkkookkkkk",
    "kkkkkkkkkppkkkkk",
    "kkkkkkkkkkkkkkkk",
    "kkkkkkkkkkkkkkkk",
    "kkkkkkkkkkkkkkkk",
    "kkkkokkkkkkkkkkk",
    "kkkkkkkkkkkkkkkk",
    "kkkkkkkkkkkkkkkk",
    "kkkkkkkkkkkkkkkk",
    "kkkkkkkkkkkkkkkk",
    "kkkkkkkkkkkkkkkk"
  ],
  "stone": [
    "llllllllllllllll",
    "llaaaamllaaaaall",
    "laaaaaaamaaaaaal",
    "laaaaaaaaaaaaaal",
    "laaaaaaamaaaaaal",
    "laaaaaaamaaaaaml",
    "lmaaaaanlnnnnnll",
    "lllllllllaaaaall",
    "llaaaamlmaaaaaal",
    "laaaaaaaaaaaaaal",
    "laaaaaaamaaaaaal",
    "laaaaaaaaaaaaaal",
    "laaaaaaamaaaaaal",
    "laaaaaammaaaaaal",
    "llaaaaallaaaaall",
    "llllllllllllllll"
  ],
  "soil": [
    "iiiiiiiiiiiiiiii",
    "iiiiiiiiiiiiiiii",
    "iiiihhiiiihhiiii",
    "iiihhhiiiihhiiii",
    "iiihhhiiiihhhiii",
    "iiihhhiiiihhhiii",
    "iiihhhiiiihhhiii",
    "iiihhhiiiihhiiii",
    "iiihhhiiiihhiiii",
    "iiihhhiiiihhhiii",
    "iiihhhiiiihhhiii",
    "iiihhhiiiihhiiii",
    "iiihhhiiiihhiiii",
    "iiihhhiiiihhhiii",
    "iiiiiiiiiiiiiiii",
    "iiiiiiiiiiiiiiii"
  ]
}
